gui: "127.0.0.1:9999"
proxies:
  - alias: iltruv1d
    enabled: true
    listen: "127.0.0.1:58881"
    mysql: "gz-cdb-iltruv1d.sql.tencentcdb.com:58881"
  - alias: r1gv6x0t
    enabled: true
    listen: "127.0.0.1:59904"
    mysql: "gz-cdb-r1gv6x0t.sql.tencentcdb.com:59904"