gui: "127.0.0.1:9999"
proxies:
  - alias: db1
    enabled: true
    listen: "127.0.0.1:58881"
    mysql: "db1:58881"
  - alias: db2
    enabled: true
    listen: "127.0.0.1:59904"
    mysql: "db2:59904"